version: "2"
services:
  mw-dhis2-integration:
    image: openlmismw/dhis2-integration
    links:
      - db
      - log
    ports:
      - "8080"
    env_file: .env
  db:
    image: openlmis/postgres:9.6
    env_file: .env
  log:
    image: openlmis/rsyslog:1
    volumes:
      - '../logs/dhis2-integration:/var/log'
